### ISSUE TITLE
"lookup" function not working for pub keys

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/cos-ansible-base#28]
For some reason, using the `lookup` function for public ssh keys doesn't seem to be working. 

``` yaml
genericusers_users:
   # ...
  ssh_keys:
     - "{{ lookup('file', 'group_vars/pubkeys/sloria.pub') }}"
```

When the genericusers role runs, the ssh keys are not copied (the `ssh_keys` variable appears to be an empty list.

@lyndsysimon is seeing the same thing.

For now, I'm just copying the pubkeys directly.
